launcher:
    acceptUpdates: false
    buildNumber: 0
    buildType: RECOMMENDED
    latestLWJGL: false
    memory: 0
    retryLogin: true
client:
    advancedOpenGL: 1
    anaglyph3D: false
    automateMode: 0
    automatePerformance: true
    autosave: 0
    betterGrass: 0
    brightnessSlider: 1.0
    buildNumber: 0
    buildType: RECOMMENDED
    chatGrabsMouse: true
    clearWater: false
    clipboardaccess: false
    delayedTooltips: false
    fancyBiomeColors: true
    fancyClouds: false
    fancyFog: true
    fancyGraphics: false
    fancyGrass: true
    fancyLight: false
    fancyParticles: true
    fancyTrees: false
    fancyWater: true
    fancyWeather: false
    farView: false
    fastDebug: 0
    fastLogin: false
    guiScale: 0
    highlightMentions: true
    mipmapsPercent: 0.0
    performance: 0
    preloadedChunks: 0
    renderDistance: 2
    showChatColors: true
    showDamageAlerts: true
    showJoinMessages: true
    signDistance: 8
    sky: true
    smoothFPS: false
    smoothLighting: 1.0
    stars: true
    time: 0
    viewBobbing: false
    voidFog: true
    waterBiomeColors: true
    weather: true
